server:
  port: ${SERVER_PORT:8080}
spring:
  application.name: ${APPLICATION_NAME:keycloak-demo}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8484/auth/realms/my_realm
        registration:
          keycloak:
            client-id: my_client
    resource-server:
      jwk:
        jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:8484/auth/realms/my_realm/protocol/openid-connect/certs}
keycloak:
  auth-server-url: http://localhost:8484/auth
#  what's keycloak's space you will use
  realm: my_realm
  resource: my_client
  public-client: true
#  if enabled, login page don't shows
  bearer-only: false